services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - media_data:/data/media
      - ./ai-service:/ai-service
    env_file:
      - .env

volumes:
  media_data:
