# Generated by Django 6.0.3 on 2026-03-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_recordcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='record',
            name='stage',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
