# Generated by Django 6.0.3 on 2026-03-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_stage_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
