# Generated by Django 6.0.3 on 2026-03-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_record_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
