# Generated by Django 6.0.3 on 2026-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_mappin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='color',
            field=models.CharField(default='#22c55e', max_length=7),
        ),
    ]
