# Generated by Django 6.0.3 on 2026-03-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_mappin_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappin',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_pins', to='crm.record'),
        ),
    ]
